### ISSUE TITLE
Comments on Study Protocol and Study Factors are not written by ISA-Tab dump function

### ISSUE THREAD

**Issue by proccaserra** [ISA-tools/isa-api#331]
reported by @bedroesb while working on BRAPI2ISA refactoring.

**Comment by bedroesb** [comment]
@proccaserra  the comments in STUDY DESIGN DESCRIPTORS are also not printed.

**Comment by proccaserra** [comment]
@bedroesb yeah I am aware (and the bug shows in various other sections) but I have fixed it.
We'll be issuing a bug fix release shortly.

**Comment by bedroesb** [comment]
That is nice to hear, looking forward to it!

**Comment by Thyra** [comment]
I'm still having this problem in 0.10.3:

```python
from isatools.model import *
i = Investigation()
s = Study(filename="s_study.txt")
i.studies.append(s)

study_design = OntologyAnnotation(term="Study design")
study_design.comments.extend([
    Comment(name="This is a comment", value="Comment value")
])
s.design_descriptors.append(study_design)

from isatools import isatab
print(isatab.dumps(i))
```

The comment is not being printed. Is there anything else I need to do to get it shown?

**Comment by bedroesb** [comment]
I installed the latest version from github manually (so not the one on pip), to get the comments printed

**Comment by bedroesb** [comment]
https://github.com/ISA-tools/isa-api/releases/tag/v0.10.4

**Comment by Thyra** [comment]
I just installed it from the master branch (`pipenv install -e git+https://github.com/ISA-tools/isa-api#egg=isatools`) and I can confirm it seems to be fixed. Shall we close this issue then?

**Comment by bedroesb** [comment]
I guess we could do that, although I would like to see an official release of 10.4 on pip
